# Generated by Django 5.2 on 2026-01-09 01:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_victima', models.CharField(max_length=255)),
                ('clasificacion', models.CharField(choices=[('robo', 'Robo'), ('violencia', 'Violencia'), ('fraude', 'Fraude'), ('fraud', 'Fraud'), ('acoso', 'Acoso'), ('otro', 'Otro')], max_length=50)),
                ('respuesta_ia', models.TextField(blank=True, null=True)),
                ('datos_completos', models.JSONField(blank=True, default=dict, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denuncias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Denuncia',
                'verbose_name_plural': 'Denuncias',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
